In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

Answer
53713.86 and 93747.79

In [28]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv('C:/Users/cgplugs/Documents/python practise/Linear_reg/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [30]:
df.rename(columns = {"test_score(out of 10)": "test_score"}, inplace= True)
df.rename(columns = {"interview_score(out of 10)": "interview_score"}, inplace= True)
df.rename(columns = {"salary($)": "salary"}, inplace= True)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [31]:
df.test_score.median()
import math
median_test_score = math.floor(df.test_score.mean())
median_test_score

7

In [32]:
df.test_score = df.test_score.fillna(median_test_score)
df.experience = df.experience.fillna('zero')
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         7.0                7   72000
7     eleven         7.0                8   80000

In [33]:
df.experience = [w2n.word_to_num(i) for i in df.experience]
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [34]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary', axis='columns'), df.salary)

LinearRegression()

In [35]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [36]:
reg.intercept_

14992.651446693133

Find the salary of a person with 2 yr experience, 9 test score, 6 interview score

In [37]:
reg.predict([[2,9,6]])

c:\users\cgplugs\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

Y = m1 x1 + m2 x2 + m3 x3+....+ mn xn + b (where m is the coeficient and b is the intercept)

In [39]:
2922.26901502*2 + 2221.30909959*9 + 2147.48256637*6 + 14992.651446693133

53713.866771263136

Find the salary of a person with 12 yr experience, 10 test score, 10 interview score

In [40]:
reg.predict([[12,10,10]])

c:\users\cgplugs\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [41]:
2922.26901502*12 + 2221.30909959*10 + 2147.48256637*10 + 14992.651446693133

93747.79628653315

In [1]:
from sklearn.linear_model import LinearRegression

# Sample data
X = [[1], [2], [3]]  # Features
y = [2, 4, 6]        # Target variable

# Create a linear regression model
model = LinearRegression()

# Fit the model to the data
model.fit(X, y)

# Access coefficients and intercept
coefficients = model.coef_
intercept = model.intercept_

print("Coefficients:", coefficients)
print("Intercept:", intercept)


Coefficients: [2.]
Intercept: 8.881784197001252e-16
